src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Un autre utilisateur a déjà cette adresse email"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom.")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille.")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide.")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez donner une URL valide pour l'avatar.")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Les mots de passe ne correspondent pas.")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Votre introduction doit faire au moins 10 caractères.")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description doit faire au moins 100 caractères.")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * Renvoi le nom complet
     *
     * @return string
     */
    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * Initialise le slug si il n'y en a pas
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if (empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();

        $role[] = 'ROLE_USER';

        return $role;

    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    {
        //
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
        //
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdType extends ApplicationType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class,
                $this->getConfiguration("Titre", "Tapez un super titre pour votre annonce !"))

            ->add('introduction', TextType::class,
                $this->getConfiguration("Introduction", "Donnez une description globale de l'annonce"))

            ->add('content', TextareaType::class,
                $this->getConfiguration("Description détaillé", "Taper une bonne description"))

            ->add('rooms', IntegerType::class,
                $this->getConfiguration("Nombre de chambre", "Nombre de chambre disponibles"))

            ->add('price', MoneyType::class,
                $this->getConfiguration("Prix par nuit", "Indiquer le prix pour une nuit"))

            ->add('slug', TextType::class,
                $this->getConfiguration("Chaine URL", "Adresse web (automatique)",
                    ['required' => false] ))

            ->add('coverImage', UrlType::class,
                $this->getConfiguration("URL de l'image principale", "Donnez l'adresse de l'image"))

            // Mise en place d'un sous formulaire qui peut se répéter à la demande
            ->add('images', CollectionType::class,
                [
                    'entry_type' => ImageType::class,
                    'allow_add' => true,
                    'allow_delete' => true
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Repository\AdRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     *
     * @param AdRepository $adRepository
     * @return Response
     */
    public function index(AdRepository $adRepository)
    {
        $ads = $adRepository->findAll();

        return $this->render('ad/index.html.twig',
        [
            'ads' => $ads,
        ]);
    }

    /**
     * Céeer une annonce
     *
     * @Route("/ads/new", name="ads_create")
     *
     * @IsGranted("ROLE_USER")
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $manager )
    {
        $user = $this->getUser();
        $ad = new Ad();
        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid())
        {
//          Prise en compte des nouvelles images pour les faire persister avant de faire persister l'annonce
            foreach ($ad->getImages() as $image)
            {
                $image->setAd($ad);
                $manager->persist($image);
            }
            
            $ad->setAuthor($user);

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash
            (
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enrengistré ! "
            );

            return $this->redirectToRoute('ads_show',
            [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/new.html.twig',
        [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher le formulaire d'édition
     *
     * @Route("/ads/{slug}/edit", name="ads_edit")
     *
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas")
     * @param  Ad $ad
     * @param  Request $request
     * @param  EntityManagerInterface $manager
     * @return Response
     */
    public function edit(Ad $ad, Request $request, EntityManagerInterface $manager)
    {

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
//          Prise en compte des nouvelles images pour les faire persister avant de faire persister l'annonce
            foreach ($ad->getImages() as $image)
            {
                $image->setAd($ad);
                $manager->persist($image);
            }

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash
            (
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été modifié ! "
            );

            return $this->redirectToRoute('ads_show',
                [
                    'slug' => $ad->getSlug()
                ]);
        }

        return $this->render('ad/edit.html.twig',
        [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * Affiche une annonce
     *
     * @Route("/ads/{slug}", name="ads_show")
     * @param Ad $ad
     * @return Response
     */
    public function show (Ad $ad)
    {

//        $ad = $repo->findOneBySlug($slug);

        return $this->render('ad/show.html.twig',
            [
                'ad' => $ad
            ]);
    }

    /**
     * Delete
     * Permet de supprimer une annonce
     *
     * @Route("/ads/{slug}/delete", name="ads_delete")
     *
     * @Security("is_granted('ROLE_USER') and user == ad.getAuthor()", message="Vous n'avez pas le droit d'accèder à cette ressource")
     * @param Ad $ad
     * @param EntityManagerInterface $manager
     * @return RedirectResponse
     */
    public function delete(Ad $ad, EntityManagerInterface $manager)
    {
        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            'succes',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée !"
        );

        return $this->redirectToRoute("ads_index");
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug': ad.slug}) %}

<div class="col md-3">
    <div class="card bg-light mb-3">

        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strong>{{ ad.price }}&euro; / nuit</strong> <br>
            <small> Pas encore noté</small>
        </div>

        <a href="{{ url }}">
            <img src="{{ ad.coverImage }}" alt="Image de l'appartement" style="height: 200px; width: 100%; display: block">
        </a>

        <div class="card-body">
            <h4 class="card-body">
                <a href="{{ url }}">
                    {{ ad.title }}
                </a>
            </h4>
            <p class="card-text">{{ ad.introduction }}</p>
            <a href="{{ url }}" class="btn-secondary">En savoir plus</a>

            {% if  app.user and app.user == ad.author%}
                <a href="{{ path('ads_edit', {{ 'slug': ad.slug }}) }}" class="btn btn-secondary">Réserver !</a>
            {% endif %}

        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %}

    <p>Ici, vous pouvez ajouter vos propres images ! </p>

    {{ form_widget(form) }}

    <input type="hidden" id="widgets-counter" value="0">

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajoutez une image.</button>
    </div>

{% endblock %}

{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_widgets %}

    <div class="form-group" id="block_{{ id }}">

        <div class="row">
            <div class="col-10">

                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                    </div>

                    <div class="col">
                        {{ form_widget(form.caption) }}
                    </div>
                </div>

            </div>
            {#TODO Le boutton  ne s'affiche pas#}
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
            </div>

        </div>

    </div>

{% endblock %}

templates/ad/_form_theme.html.twig
{% block _ad_pictures_widget %}
    <p>Ajouter une ou plusieurs photos</p>

    {{ form_widget(form) }}

    <input type="hidden" id="widgets-counter" value="0">

    <div class="form-group">
        <button type="button" id="add_picture" class="btn btn-primary"> <i class="fa fa-images"></i>&nbsp; Ajouter une photo &nbsp;<i class="fa fa-plus"></i></button>
    </div>
{% endblock %}

{% block _ad_pictures_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_pictures_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger"> X </button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %} Modifier une annonce {% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

    <diV class="container">

        <h1>Modifier l'annonce : {{ ad.title }}</h1>

        {{ form_start(form)}}

        {{ form_widget(form) }}

        <button type="submit" class="btn btn-primary"> Modifier l'annonce. </button>

        {{ form_end(form) }}

    </diV>

{% endblock %}


{% block javascripts %}

    <script src="{{ asset('js/ad.js') }}"> </script>

{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces{% endblock %}

{% block body %}

    <div class="container">
        <h1 class="my-3">Voici les annonces de nos hôtes</h1>

        <div class="row">
            {% for ad in ads %}
                {% include 'ad/_ad.html.twig' %}
            {% endfor %}
        </div>
    </div>


{% endblock %}

templates/ad/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} Création d'une annonce {% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

    <diV class="container">

        <h1>Créer une nouvelle annonce</h1>

        {{ form_start(form)}}

        {{ form_widget(form) }}

        <button type="submit" class="btn btn-primary"> Créer la nouvelle annonce. </button>

        {{ form_end(form) }}

    </diV>

{% endblock %}

{% block javascripts %}

    <script src="{{ asset('js/ad.js') }}"> </script>

{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ ad.title }} {% endblock %}

{% block body %}

    <div class="ad-title" style="background-image: url({{ ad.coverImage }})">
        <div class="container">
            <h1>{{ ad.title }}</h1>
            <p>{{ ad.introduction }}</p>
            <p class="h2">
                <strong>{{ ad.rooms }} chambres</strong> pour <strong> {{ ad.price }} €</strong> par nuit.
            </p>
            <a href="#" class="btn btn-primary">Réserver !</a>

            {% if  app.user and app.user == ad.author%}
                <a href="{{ path('ads_edit', {{ 'slug': ad.slug }}) }}" class="btn btn-secondary">Réserver !</a>

                <a href="{{ path('ads_delete', {'slug': ad.slug}) }}" class="btn btn-danger"
                   onclick="return confirm(`Êtes vous sur de vouloir supprimer l'annonce : {{ ad.title }} `)">Supprimer l'annonce</a>

            {% endif %}


        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3"> {{ ad.content | raw }}
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}"
                                {% if loop.first %}class="active">{% endif %}</li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                            <div class="carousel-item {% if loop.first %}active {% endif %}">
                                <img src="{{ image.url }}" class="d-block w-100" alt="...">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ ad.title }}</h5>
                                    <p>{{ image.caption }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col">
                {% set a = ad.author %}
                <div class="row">

                    <div class="col-3">
                        <a href="{{ path('user_show', {'slug': a.slug}) }}">
                            <img src="{{ a.picture }}" class="avatar avatar-medium" alt="Avatar de {{ a.fullName }}">
                        </a>
                    </div>

                    <div class="col">
                        <a href="{{ path('user_show', {'slug': a.slug}) }}">
                            <h3>{{ a.fullName }}</h3>
                        </a>
                        <span class="badge badge-primary"> {{ a.ads | length }} annonces</span>
                    </div>

                </div>
                {{ a.description | raw }}
            </div>
        </div>
    </div>


{% endblock %}